[phases.build]
cmd = "vite build && esbuild server/index.production.ts --platform=node --packages=external --bundle --format=esm --outdir=dist"

[start]
cmd = "NODE_ENV=production node dist/index.production.js"